[package]
name = "rs-units-interpreter"
version = "0.1.0"
authors = ["milesziemer"]
edition = "2021"

# For compiling to wasm
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.78"
