version: "3"

services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${CONTAINER_NAME}:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/${CONTAINER_NAME}
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs
